# Generated by Django 4.2.3 on 2023-08-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotificationsubscriber',
            name='device_token',
            field=models.CharField(max_length=555),
        ),
    ]
