# Generated by Django 4.2.3 on 2023-08-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_pushnotificationsubscriber_device_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushnotificationsubscriber',
            old_name='device_token',
            new_name='endpoint',
        ),
    ]
