# Generated by Django 4.2.3 on 2023-08-09 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('voice', 'Voice'), ('video', 'Video')], max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('call_from', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='send_call', to=settings.AUTH_USER_MODEL)),
                ('call_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_call', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
