# Generated by Django 4.2.3 on 2023-07-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_chatthread_delete_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_message_thread', to='chat.chatthread'),
        ),
    ]
