# Generated by Django 4.2.3 on 2023-07-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_group_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='file_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupchatmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
