# Generated by Django 4.2.3 on 2023-07-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chatmessage_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatmessage',
            name='file_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
