# Generated by Django 4.2.3 on 2023-07-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_chatmessage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='<function user_upload_path at 0x0000021450362EF0>/thumbnails'),
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='file_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='<function group_upload_path at 0x0000021450362E60>/thumbnails'),
        ),
    ]
