# Generated by Django 4.2.3 on 2023-07-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('channel_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('video', 'Video'), ('file', 'File')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_paid', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='server/avatar')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='server/cover')),
                ('description', models.CharField(blank=True, max_length=190, null=True)),
                ('category', models.CharField(choices=[('gaming', 'Gaming'), ('educational', 'Educational'), ('science-and-tech', 'Science and Tech'), ('entertainment', 'Entertainment')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
